# Generated by Django 5.2.7 on 2025-11-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='account_paid',
            new_name='amount_paid',
        ),
    ]
